apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    debug
        Daemon       Off

    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Tag          kube.*
        Parser       docker

    [FILTER]
        Name            kubernetes
        Match           kube.*

    [FILTER]
        Name            grep
        Match           kube.*
        Regex           $kubernetes['namespace_name'] default

    # Rewriting the tag to include pod_name and container_name
    [FILTER]
        Name            rewrite_tag
        Match           kube.*
        Rule            $kubernetes['namespace_name']   ^(.*)$   $kubernetes['labels']['app'].$kubernetes['pod_name'].$kubernetes['container_name'].log   false

    [OUTPUT]
        Name         file
        Match        *
        Path         /fluent-bit/logs
        Format       template
        Mkdir        true
        Template     {log}