apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: fluentd-forwarder
  namespace: tpsm-logging
spec:
  file:
    path: "/service-logs/${tag}-%Y%m%d-%H-%M.log"
    format:
      type: json