apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: fluentd-forwarder
  namespace: tpsm-logging
spec:
  file:
    path: "/service-logs/${service}/${pod}/${tag}.log"
    buffer:
      tags: pod, service,tag, time
      timekey: 1m
      timekey_wait: 10s
      timekey_use_utc: true
    format:
      type: json

